import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, FAQAndCTA, JsonLd, ProseBody } from "@/components/content/PageBits";
import { fetchGlossaryTermBySlug, fetchGlossaryTerms } from "@/lib/glossary";
import { buildMetadata } from "@/lib/metadata";
export const revalidate = 3600;
export async function generateStaticParams() { const terms = await fetchGlossaryTerms(); return terms.map((term) => ({ slug: term.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const term = await fetchGlossaryTermBySlug(slug); if (!term) return buildMetadata("Glossary", "Short-term rental terms explained.", `/glossary/${slug}`); return buildMetadata(term.seoTitle, term.seoDescription, `/glossary/${term.slug}`); }
export default async function GlossaryTermPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const term = await fetchGlossaryTermBySlug(slug); if (!term) notFound(); return <div className="min-h-screen bg-background pb-20 pt-8"><div className="container mx-auto px-4 max-w-screen-xl"><Breadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Glossary', href: '/glossary' }, { label: term.term }]} /><div className="max-w-4xl"><div className="mb-8"><div className="text-sm font-bold text-primary uppercase tracking-wider mb-2">{term.definitionPrefix || 'Definition'}</div><h1 className="font-display text-4xl md:text-6xl font-bold mb-4">What is {term.term}?</h1><p className="text-xl text-muted-foreground">{term.definition}</p></div><ProseBody blocks={term.body} />{term.relatedTerms.length ? <section className="mt-12"><h2 className="font-display text-2xl font-bold mb-4">Related Terms</h2><div className="flex flex-wrap gap-3">{term.relatedTerms.map((item) => <Link key={item} href={`/glossary/what-is-${item.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`} className="rounded-full border border-border px-4 py-2 text-sm hover:text-primary">{item}</Link>)}</div></section> : null}</div><FAQAndCTA faqs={term.faqs} faqTitle={term.faqTitle} ctaTitle={term.ctaTitle} ctaText={term.ctaText} ctaPrimaryButton={term.ctaPrimaryButton} /></div><JsonLd data={{ '@context': 'https://schema.org', '@type': 'DefinedTerm', name: term.term, description: term.definition }} /></div>; }
