import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Calculator, ChefHat, Bed, TrendingUp, DollarSign, Hammer, ArrowRight, CheckCircle2, Home, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { buildMetadata } from "@/lib/metadata";

export const revalidate = 3600;
export const metadata = buildMetadata("Tools", "Calculator tools for real estate operators.", "/tools");

const tools = [{ slug: "renovation-calculator", category: "renovations", title: "Renovation ROI", description: "Calculate the return on investment for your rental property renovations.", icon: Hammer, href: "/tools/renovations/renovation-calculator", popular: true }, { slug: "rental-yield-calculator", category: "finance", title: "Rental Yield Calc", description: "Calculate gross and net rental yields for your investment property.", icon: TrendingUp, href: "/tools/finance/rental-yield-calculator", popular: true }, { slug: "airbnb-profit-calculator", category: "booking", title: "Airbnb Profit Calc", description: "Estimate monthly earnings based on occupancy and seasonality.", icon: DollarSign, href: "/tools/booking/airbnb-profit-calculator", popular: false }, { slug: "cleaning-fee-calculator", category: "booking", title: "Cleaning Fee Estimator", description: "Set competitive pricing for your cleaning fees.", icon: CheckCircle2, href: "/tools/booking/cleaning-fee-calculator", popular: false }, { slug: "kitchen-cost-calculator", category: "renovations", title: "Kitchen Cost Calc", description: "Full gut renovation estimates including cabinets and appliances.", icon: ChefHat, href: "/tools/renovations/kitchen-cost-calculator", popular: false }, { slug: "bedroom-reno-calculator", category: "renovations", title: "Bedroom Reno Calc", description: "Calculate flooring, paint, and furnishing costs.", icon: Bed, href: "/tools/renovations/bedroom-reno-calculator", popular: false }];
const categories = [{ id: "all", label: "All Tools" }, { id: "renovations", label: "Renovations" }, { id: "finance", label: "Finance" }, { id: "booking", label: "Booking" }];

export default function ToolsIndexPage() {
  const activeCategory = "all";
  const filteredTools = tools;
  const getCategoryTitle = () => "Free Property Management Tools";

  return <div className="min-h-screen bg-background pt-24 pb-20"><div className="container mx-auto px-4 max-w-7xl"><div className="text-center max-w-3xl mx-auto mb-16"><div className="flex items-center justify-center text-sm text-muted-foreground gap-2 overflow-x-auto whitespace-nowrap mb-6"><Link href="/" className="hover:text-primary transition-colors flex items-center gap-1"><Home className="h-3 w-3" /> Home</Link><ChevronRight className="h-4 w-4 flex-shrink-0" /><Link href="/tools" className={cn("hover:text-primary transition-colors", activeCategory === "all" ? "text-foreground font-medium" : "")}>Free Tools</Link></div><Badge className="bg-primary/10 text-primary border-primary/20 mb-6 px-4 py-1.5 text-sm font-bold uppercase tracking-wider">Free Resources</Badge><h1 className="font-display text-4xl md:text-6xl font-bold mb-6">{getCategoryTitle()}</h1><p className="text-xl text-muted-foreground leading-relaxed">Calculators and templates to run your portfolio better. Professional-grade tools, completely free.</p></div><div className="flex flex-wrap justify-center gap-2 mb-16">{categories.map((cat) => <Link key={cat.id} href={cat.id === "all" ? "/tools" : `/tools/${cat.id}`}><Button variant={activeCategory === cat.id ? "default" : "outline"} className={cn("rounded-full px-6 h-10 font-bold transition-all", activeCategory === cat.id ? "bg-primary text-white shadow-lg shadow-primary/20 hover:bg-primary/90" : "bg-background text-muted-foreground hover:text-foreground border-border hover:border-primary/50")}>{cat.label}</Button></Link>)}</div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">{filteredTools.map((tool) => <Link key={tool.slug} href={tool.href}><div className="group h-full bg-card border border-border hover:border-primary/50 rounded-3xl p-8 shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity" /><div className="relative z-10"><div className="flex justify-between items-start mb-6"><div className="h-14 w-14 rounded-2xl bg-primary/10 text-primary flex items-center justify-center group-hover:scale-110 transition-transform duration-300"><tool.icon className="h-7 w-7" /></div>{tool.popular && <Badge variant="secondary" className="bg-yellow-100 text-yellow-700 font-bold border-yellow-200">Popular</Badge>}</div><h3 className="font-display text-xl font-bold mb-3 group-hover:text-primary transition-colors">{tool.title}</h3><p className="text-muted-foreground text-sm leading-relaxed mb-6">{tool.description}</p><div className="mt-auto pt-4 flex items-center text-primary font-bold text-sm gap-2 opacity-80 group-hover:opacity-100 group-hover:translate-x-1 transition-all">Try Tool <ArrowRight className="h-4 w-4" /></div></div></div></Link>)}</div></div></div>;
}
